# Generated by Django 4.2.4 on 2023-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=15
            ),
        ),
    ]
