# Generated by Django 4.2.4 on 2023-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0002_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, null=True, to="instagram.image"),
        ),
    ]
