# Generated by Django 4.2.4 on 2023-08-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='instagram.video'),
        ),
    ]
