# Generated by Django 4.2.1 on 2023-08-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0006_comment_story_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(to="instagram.image"),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.ManyToManyField(to="instagram.video"),
        ),
    ]
