# Generated by Django 4.2.1 on 2023-08-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0009_alter_post_images_alter_post_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, to="instagram.image"),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.ManyToManyField(blank=True, to="instagram.video"),
        ),
    ]
