# Generated by Django 4.2.1 on 2023-08-08 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0010_alter_post_images_alter_post_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
