# Generated by Django 4.2.1 on 2023-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0014_alter_story_highlight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/images/default_profile_picture",
                upload_to="profile/images",
            ),
        ),
    ]
